spring:
  data:
    rest:
      basePath: "/api"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.70.89:3306/crm_core?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: silkroad
    password: 83lchichucrodrl
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      naming:
#       默认是 SpringNameingStrategyStandardImpl 会将所有的驼峰式转为下划线时，无论是否用@Column显示指定
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
